<?php
/**
 * Created by PhpStorm.
 * User: Joe <>
 * Date: 2019/3/18
 * Time: 20:47
 */

namespace app\api\controller;


use think\Request;
use think\Response;

class Mobile extends ApiBase
{
    /**
     * 跨域会多请求一个OPTIONS
     * @author Joe <QQ 137294789>
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (strtoupper(request()->method()) == "OPTIONS") {
            die();
        }
    }

    /**
     * 个人中心中的我的游戏记录
     * @author Joe <QQ 137294789>
     * @param Request $request
     * @return mixed
     */
    public function myGameList(Request $request)
    {
        return $this->apiReturn(

            $this->logicMobile->myGameList($request)

        );
    }

    /**
     * 下载游戏
     * @author Joe <QQ 137294789>
     * @param Request $request in game_id
     * @return mixed
     */
    public function downGame(Request $request)
    {
        return $this->apiReturn(

            $this->logicMobile->downGame($request)

        );
    }

    /**
     * 领取游戏礼包
     * @author Joe <QQ 137294789>
     * @param Request $request in member_id 用户ID
     * @return mixed
     */
    public function getGift(Request $request)
    {
        return $this->apiReturn(

            $this->logicMobile->getMobileGift($request)

        );
    }

    /**
     * 获取礼包列表
     * @author Joe <QQ 137294789>
     * @param Request $request in  page&rows &group_id分组ID
     * @return mixed
     */
    public function getGiftList(Request $request)
    {
        return $this->apiReturn(

            $this->logicMobile->getGiftList($request)

        );
    }

    /**
     * 手机主页页面
     * @author Joe <QQ 137294789>
     * @return mixed
     */
    public function index()
    {
        return $this->apiReturn(

            $this->logicMobile->index()

        );
    }

    /**
     * 手机游戏分类列表
     * @author Joe <QQ 137294789>
     * @return mixed
     */
    public function getGameGroup()
    {
        return $this->apiReturn(

            $this->logicMobile->getCtegory()

        );
    }

    /**
     * 获取游戏列表
     * @author Joe <QQ 137294789>
     * @param Request $request in group_id 游戏分类ID
     * @return array
     */
    public function getGameList(Request $request)
    {
        return $this->apiReturn(

            $this->logicMobile->getGameList($request)

        );
    }

    /**
     * 游戏开始
     * @author Joe <QQ 137294789>
     * @param Request $request in [game_id & member_id]
     * @return mixed
     */
    public function gamePaly(Request $request)
    {
        return $this->apiReturn(

            $this->logicMobile->play($request)

        );
    }
}